dataset_name: "ViTextVQA"
data_dir: "./datasets"
vocab_path: "configs/data/term_vocab.txt"
viet_vocab_path: "configs/data/viet_vocab.txt"

loss_ablation_mode: "all"
ablation_use_qaclip: true
ablation_use_vs: true
ablation_use_ocr: true

output_dir: "./output/pretrain"
logging_dir: "./output/pretrain/logs"
resume_from_checkpoint: null
resume_checkpoint_id: ""

seed: 42
num_train_epochs: 10
per_device_train_batch_size: 4
per_device_eval_batch_size: 4
gradient_accumulation_steps: 4
learning_rate: 0.0001
weight_decay: 0.01
warmup_ratio: 0.1
lr_scheduler_type: "cosine"
max_grad_norm: 1.0

logging_steps: 10
eval_strategy: "steps"
eval_steps: 1050
save_strategy: "steps"
save_steps: 1050
save_total_limit: 3

metric_for_best_model: "pretrain_acc"
greater_is_better: true
load_best_model_at_end: true
remove_unused_columns: false
predict_with_generate: false

optim: "adamw_torch"
dataloader_num_workers: 4
dataloader_pin_memory: true
disable_tqdm: false
fp16: false
report_to: "none"
